# Generated by Django 4.1.7 on 2023-03-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='name',
        ),
        migrations.RemoveField(
            model_name='social',
            name='url',
        ),
        migrations.AddField(
            model_name='social',
            name='facebook',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social',
            name='instagram',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social',
            name='linkedin',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social',
            name='twitter',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
