# Generated by Django 4.1.7 on 2023-04-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_remove_social_name_remove_social_url_social_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='desktop_logo',
            field=models.ImageField(upload_to='LOGOS'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='mobile_logo',
            field=models.ImageField(upload_to='LOGOS'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='website_icon',
            field=models.ImageField(upload_to='LOGOS'),
        ),
    ]
