# Generated by Django 4.1.7 on 2023-03-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_time',
            field=models.CharField(max_length=6),
        ),
    ]
