# Generated by Django 4.1.7 on 2023-03-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='time_view',
            field=models.CharField(default=2, max_length=4),
        ),
    ]
