# Generated by Django 4.1.7 on 2023-03-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0002_ability_time_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('text', models.TextField()),
                ('time_view', models.CharField(default=2, max_length=4)),
            ],
        ),
    ]
