# Generated by Django 4.1.7 on 2023-03-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0003_abilityinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_time', models.IntegerField()),
                ('completed_projects', models.IntegerField()),
                ('satisfied_customers', models.IntegerField()),
                ('prizes_won', models.IntegerField()),
            ],
        ),
    ]
